INFO     test_slider_captcha:test_slider_captcha.py:28 🟢 ----- test_slider_captcha_handler -----
INFO     test_slider_captcha:base.py:238 🟢 开始处理滑块验证码...
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:77 🔵 拦截到验证码请求，开始下载验证码
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:77 🔵 拦截到验证码请求，开始下载验证码
INFO     mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:89 🟢 验证码图片保存成功
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
WARNING  test_slider_captcha:base.py:186 🟠 没找到滑块坐标
ERROR    test_slider_captcha:base.py:262 🔴 滑块拖动失败，刷新验证码重试
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 260, in handle
    await self._drag_to_breach()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/captcha/slider_captcha/base.py", line 187, in _drag_to_breach
    raise Exception('没找到滑块坐标')
Exception: 没找到滑块坐标
DEBUG    mypy.lib.playwright.captcha.slider_captcha.qcloud:qcloud.py:61 🔵 无需刷新验证码
INFO     test_slider_captcha:base.py:147 🟢 ---------- 验证码验证通过 ----------