WARNING  mypy.lib.llm.core.helper:before_sleep.py:65 Retrying mypy.lib.llm.core.helper.OpenAIBaseHelper.chat in 3.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Your account co2mu8o3r072r8fgnkv0<ak-erfxkb8jg5g111fix4h1> request reached max requset: 3, please try again after 1 seconds', 'type': 'rate_limit_reached_error'}}.
WARNING  mypy.lib.llm.core.helper:before_sleep.py:65 Retrying mypy.lib.llm.core.helper.OpenAIBaseHelper.chat in 6.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Your account co2mu8o3r072r8fgnkv0<ak-erfxkb8jg5g111fix4h1> request reached max requset: 3, please try again after 1 seconds', 'type': 'rate_limit_reached_error'}}.
WARNING  mypy.lib.llm.core.helper:before_sleep.py:65 Retrying mypy.lib.llm.core.helper.OpenAIBaseHelper.chat in 12.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Your account co2mu8o3r072r8fgnkv0<ak-erfxkb8jg5g111fix4h1> request reached max requset: 3, please try again after 1 seconds', 'type': 'rate_limit_reached_error'}}.
WARNING  mypy.lib.llm.core.helper:before_sleep.py:65 Retrying mypy.lib.llm.core.helper.OpenAIBaseHelper.chat in 15.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Your account co2mu8o3r072r8fgnkv0<ak-erfxkb8jg5g111fix4h1> request reached max requset: 3, please try again after 1 seconds', 'type': 'rate_limit_reached_error'}}.