INFO     conftest:conftest.py:121 ðŸŸ¢ [åˆ›å»º]æµ‹è¯•ç”¨ä¾‹è¾“å‡ºç›®å½•: /home/runner/work/Python/Python/mypy/tests/lib/pdf/_out/test_pdf_handler
DEBUG    /home/runner/work/Python/Python/mypy/utils/tools.py:tools.py:235 ðŸ”µ æ­£åœ¨æ‰§è¡Œå‘½ä»¤: ['pdftoppm', '-jpeg', '/home/runner/work/Python/Python/mypy/assets/media/pdf.pdf', '/home/runner/work/Python/Python/mypy/tests/lib/pdf/_out/test_pdf_handler/test_pdf2image_by_pdftoppm/slide']
ERROR    /home/runner/work/Python/Python/mypy/utils/tools.py:tools.py:261 ðŸ”´ å‘½ä»¤: ['pdftoppm', '-jpeg', '/home/runner/work/Python/Python/mypy/assets/media/pdf.pdf', '/home/runner/work/Python/Python/mypy/tests/lib/pdf/_out/test_pdf_handler/test_pdf2image_by_pdftoppm/slide'] æ‰§è¡Œå¤±è´¥ï¼Œè¾“å‡º: I/O Error: Couldn't open file '/home/runner/work/Python/Python/mypy/assets/media/pdf.pdf': No such file or directory.
NoneType: None