INFO     conftest:conftest.py:121 🟢 [创建]测试用例输出目录: /home/runner/work/Python/Python/mypy/tests/lib/pexels/_out/test_pexels
INFO     mypy.lib.pexels.video:video.py:166 🟢 正在搜索 mountain 相关的视频...
DEBUG    mypy.lib.pexels.video:video.py:132 🔵 正在搜索视频: https://api.pexels.com//videos/search?query=mountain&per_page=20&orientation=landscape
ERROR    mypy.lib.pexels.video:video.py:145 🔴 搜索视频失败: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/Python/Python/mypy/lib/pexels/video.py", line 138, in _search_videos
    response = r.json()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO     mypy.lib.pexels.video:video.py:170 🟢 过滤搜索到的视频
INFO     mypy.lib.pexels.video:video.py:174 🟢 找到 0 条与 “mountain” 相关，且符合要求的视频
INFO     mypy.lib.pexels.video:video.py:166 🟢 正在搜索 cat 相关的视频...
DEBUG    mypy.lib.pexels.video:video.py:132 🔵 正在搜索视频: https://api.pexels.com//videos/search?query=cat&per_page=20&orientation=landscape
ERROR    mypy.lib.pexels.video:video.py:145 🔴 搜索视频失败: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/Python/Python/mypy/lib/pexels/video.py", line 138, in _search_videos
    response = r.json()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO     mypy.lib.pexels.video:video.py:170 🟢 过滤搜索到的视频
INFO     mypy.lib.pexels.video:video.py:174 🟢 找到 0 条与 “cat” 相关，且符合要求的视频
INFO     mypy.lib.pexels.video:video.py:184 🟢 总共搜集到: 0 条视频，时长总和为 0
WARNING  mypy.lib.pexels.video:video.py:188 🟠 注意！！！未下载够指定的视频时长
INFO     mypy.lib.pexels.video:video.py:88 🟢 开始下载视频...
INFO     mypy.lib.pexels.video:video.py:111 🟢 视频下载完成，保存路径: /home/runner/work/Python/Python/mypy/tests/lib/pexels/_out/test_pexels/test_pexels_get_videos