{"uid":"c9b6de88a4e81ae4","name":"test_logger_filename","fullName":"lib.test_log#test_logger_filename","historyId":"901cfb7a0c62ce3f02d30978a80a1834","time":{"start":1713619830266,"stop":1713619830268,"duration":2},"status":"skipped","statusMessage":"XFAIL 如果日志格式不包含文件名，则可能失败\n\nAssertionError: assert None is not None\n +  where None = <function search at 0x7f502b7b7280>('\\\\[test_log.py:\\\\d+\\\\]: .*test message for logging', '\uD83D\uDFE2 test message for logging\\n')\n +    where <function search at 0x7f502b7b7280> = re.search\n +    and   '\uD83D\uDFE2 test message for logging\\n' = CaptureResult(out='\uD83D\uDFE2 test message for logging\\n', err='').out","statusTrace":"capsys = <_pytest.capture.CaptureFixture object at 0x7f50231104f0>\n\n    @pytest.mark.xfail(reason='如果日志格式不包含文件名，则可能失败')\n    def test_logger_filename(capsys):\n        logger = get_logger(__name__)\n        test_message = \"test message for logging\"\n    \n        # 记录一条日志\n        logger.info(test_message)\n    \n        # 使用 capsys 来捕获日志输出\n        captured = capsys.readouterr()\n        print(captured)\n    \n        # 检查输出中是否包含正确的文件名\n        expected_filename = os.path.basename(__file__)\n        print(expected_filename)\n        print(captured.out)\n        # 正则匹配，确保日志中出现了当前文件的文件名\n>       assert re.search(\n            rf\"\\[{expected_filename}:\\d+\\]: .*{test_message}\", captured.out) is not None\nE       AssertionError: assert None is not None\nE        +  where None = <function search at 0x7f502b7b7280>('\\\\[test_log.py:\\\\d+\\\\]: .*test message for logging', '\uD83D\uDFE2 test message for logging\\n')\nE        +    where <function search at 0x7f502b7b7280> = re.search\nE        +    and   '\uD83D\uDFE2 test message for logging\\n' = CaptureResult(out='\uD83D\uDFE2 test message for logging\\n', err='').out\n\nmypy/tests/lib/test_log.py:30: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"event_loop_policy","time":{"start":1713616237329,"stop":1713616237329,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"capsys","time":{"start":1713619830265,"stop":1713619830266,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"skipped","statusMessage":"XFAIL 如果日志格式不包含文件名，则可能失败\n\nAssertionError: assert None is not None\n +  where None = <function search at 0x7f502b7b7280>('\\\\[test_log.py:\\\\d+\\\\]: .*test message for logging', '\uD83D\uDFE2 test message for logging\\n')\n +    where <function search at 0x7f502b7b7280> = re.search\n +    and   '\uD83D\uDFE2 test message for logging\\n' = CaptureResult(out='\uD83D\uDFE2 test message for logging\\n', err='').out","statusTrace":"capsys = <_pytest.capture.CaptureFixture object at 0x7f50231104f0>\n\n    @pytest.mark.xfail(reason='如果日志格式不包含文件名，则可能失败')\n    def test_logger_filename(capsys):\n        logger = get_logger(__name__)\n        test_message = \"test message for logging\"\n    \n        # 记录一条日志\n        logger.info(test_message)\n    \n        # 使用 capsys 来捕获日志输出\n        captured = capsys.readouterr()\n        print(captured)\n    \n        # 检查输出中是否包含正确的文件名\n        expected_filename = os.path.basename(__file__)\n        print(expected_filename)\n        print(captured.out)\n        # 正则匹配，确保日志中出现了当前文件的文件名\n>       assert re.search(\n            rf\"\\[{expected_filename}:\\d+\\]: .*{test_message}\", captured.out) is not None\nE       AssertionError: assert None is not None\nE        +  where None = <function search at 0x7f502b7b7280>('\\\\[test_log.py:\\\\d+\\\\]: .*test message for logging', '\uD83D\uDFE2 test message for logging\\n')\nE        +    where <function search at 0x7f502b7b7280> = re.search\nE        +    and   '\uD83D\uDFE2 test message for logging\\n' = CaptureResult(out='\uD83D\uDFE2 test message for logging\\n', err='').out\n\nmypy/tests/lib/test_log.py:30: AssertionError","steps":[],"attachments":[{"uid":"fa2f3aad93bf23ae","name":"log","source":"fa2f3aad93bf23ae.txt","type":"text/plain","size":62}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"capsys::0","time":{"start":1713619830272,"stop":1713619830272,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='如果日志格式不包含文件名，则可能失败')"},{"name":"tag","value":"lib"},{"name":"parentSuite","value":"lib"},{"name":"suite","value":"test_log"},{"name":"host","value":"fv-az1450-407"},{"name":"thread","value":"7077-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"lib.test_log"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["@pytest.mark.xfail(reason='如果日志格式不包含文件名，则可能失败')","lib"]},"source":"c9b6de88a4e81ae4.json","parameterValues":[]}