{"uid":"cffc23da9debf0ae","name":"test_y2_srt_handler","fullName":"lib.youtube.test_y2_subtitle_handler#test_y2_srt_handler","historyId":"790f8c9e97f1a64069089a1e9e93183f","time":{"start":1726243853333,"stop":1726243856098,"duration":2765},"description":"\n    测试下载youtu字幕\n    ","descriptionHtml":"<pre><code>测试下载youtu字幕\n</code></pre>\n","status":"broken","statusMessage":"tenacity.RetryError: RetryError[<Future at 0x7fce5d746490 state=finished raised TranscriptsDisabled>]","statusTrace":"self = <Retrying object at 0x7fce49f2dcd0 (stop=<tenacity.stop.stop_after_attempt object at 0x7fce867ba1f0>, wait=<tenacity.w...0x7fce95795610>, before=<function before_nothing at 0x7fce967bc8b0>, after=<function after_nothing at 0x7fce967bcc10>)>\nfn = <function Y2SubtitleHandler.download_srt at 0x7fce6d169c10>\nargs = (<mypy.lib.youtube.y2_subtitle_handler.Y2SubtitleHandler object at 0x7fce49f2d100>,)\nkwargs = {}\nretry_state = <RetryCallState 140523980643152: attempt #5; slept for 0.0; last result: failed (TranscriptsDisabled \nCould not retrie...tion needed to replicate the error. Also make sure that there are no open issues which already describe your problem!)>\ndo = <tenacity.DoAttempt object at 0x7fce4b9cf070>\n\n    def __call__(\n        self,\n        fn: t.Callable[..., WrappedFnReturnT],\n        *args: t.Any,\n        **kwargs: t.Any,\n    ) -> WrappedFnReturnT:\n        self.begin()\n    \n        retry_state = RetryCallState(retry_object=self, fn=fn, args=args, kwargs=kwargs)\n        while True:\n            do = self.iter(retry_state=retry_state)\n            if isinstance(do, DoAttempt):\n                try:\n>                   result = fn(*args, **kwargs)\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:478: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/youtube/y2_subtitle_handler.py:38: in download_srt\n    transcripts = YouTubeTranscriptApi.list_transcripts(self._video_id)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/youtube_transcript_api/_api.py:71: in list_transcripts\n    return TranscriptListFetcher(http_client).fetch(video_id)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/youtube_transcript_api/_transcripts.py:48: in fetch\n    self._extract_captions_json(self._fetch_video_html(video_id), video_id),\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <youtube_transcript_api._transcripts.TranscriptListFetcher object at 0x7fce49f2df10>\nhtml = '<!DOCTYPE html><html style=\"font-size: 10px;font-family: Roboto, Arial, sans-serif;\" lang=\"en\" darker-dark-theme dark...once=\"EjgJf9q9S-7Ki_HsAR-n3A\">if (window.ytcsi) {ytcsi.infoGel({serverTimeMs:  468.0 }, \\'\\');}</script></body></html>'\nvideo_id = 'fVcKBox97P0'\n\n    def _extract_captions_json(self, html, video_id):\n        splitted_html = html.split('\"captions\":')\n    \n        if len(splitted_html) <= 1:\n            if video_id.startswith('http://') or video_id.startswith('https://'):\n                raise InvalidVideoId(video_id)\n            if 'class=\"g-recaptcha\"' in html:\n                raise TooManyRequests(video_id)\n            if '\"playabilityStatus\":' not in html:\n                raise VideoUnavailable(video_id)\n    \n>           raise TranscriptsDisabled(video_id)\nE           youtube_transcript_api._errors.TranscriptsDisabled: \nE           Could not retrieve a transcript for the video https://www.youtube.com/watch?v=fVcKBox97P0! This is most likely caused by:\nE           \nE           Subtitles are disabled for this video\nE           \nE           If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/youtube_transcript_api/_transcripts.py:62: TranscriptsDisabled\n\nThe above exception was the direct cause of the following exception:\n\ntest_output_dir = '/home/runner/work/github-runner/github-runner/mypy/tests/lib/youtube/_out/test_y2_subtitle_handler'\n\n    def test_y2_srt_handler(test_output_dir):\n        \"\"\"\n        测试下载youtu字幕\n        \"\"\"\n        video_id = 'fVcKBox97P0'\n        en_srt_filepath = os.path.join(\n            test_output_dir, video_id + '_en.srt')\n    \n        zh_srt_filepath = os.path.join(\n            test_output_dir, video_id + '_zh.srt')\n    \n        api = Y2SubtitleHandler(video_id, en_srt_filepath, zh_srt_filepath)\n>       api.download_srt()\n\nmypy/tests/lib/youtube/test_y2_subtitle_handler.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:336: in wrapped_f\n    return copy(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:475: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:376: in iter\n    result = action(retry_state)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nrs = <RetryCallState 140523980643152: attempt #5; slept for 0.0; last result: failed (TranscriptsDisabled \nCould not retrie...tion needed to replicate the error. Also make sure that there are no open issues which already describe your problem!)>\n\n    def exc_check(rs: \"RetryCallState\") -> None:\n        fut = t.cast(Future, rs.outcome)\n        retry_exc = self.retry_error_cls(fut)\n        if self.reraise:\n            raise retry_exc.reraise()\n>       raise retry_exc from fut.exception()\nE       tenacity.RetryError: RetryError[<Future at 0x7fce5d746490 state=finished raised TranscriptsDisabled>]\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:419: RetryError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"event_loop_policy","time":{"start":1726237832833,"stop":1726237832833,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"copy_config_to_dir","time":{"start":1726243853331,"stop":1726243853332,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"test_output_dir","time":{"start":1726243853332,"stop":1726243853333,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"\n    测试下载youtu字幕\n    ","status":"broken","statusMessage":"tenacity.RetryError: RetryError[<Future at 0x7fce5d746490 state=finished raised TranscriptsDisabled>]","statusTrace":"self = <Retrying object at 0x7fce49f2dcd0 (stop=<tenacity.stop.stop_after_attempt object at 0x7fce867ba1f0>, wait=<tenacity.w...0x7fce95795610>, before=<function before_nothing at 0x7fce967bc8b0>, after=<function after_nothing at 0x7fce967bcc10>)>\nfn = <function Y2SubtitleHandler.download_srt at 0x7fce6d169c10>\nargs = (<mypy.lib.youtube.y2_subtitle_handler.Y2SubtitleHandler object at 0x7fce49f2d100>,)\nkwargs = {}\nretry_state = <RetryCallState 140523980643152: attempt #5; slept for 0.0; last result: failed (TranscriptsDisabled \nCould not retrie...tion needed to replicate the error. Also make sure that there are no open issues which already describe your problem!)>\ndo = <tenacity.DoAttempt object at 0x7fce4b9cf070>\n\n    def __call__(\n        self,\n        fn: t.Callable[..., WrappedFnReturnT],\n        *args: t.Any,\n        **kwargs: t.Any,\n    ) -> WrappedFnReturnT:\n        self.begin()\n    \n        retry_state = RetryCallState(retry_object=self, fn=fn, args=args, kwargs=kwargs)\n        while True:\n            do = self.iter(retry_state=retry_state)\n            if isinstance(do, DoAttempt):\n                try:\n>                   result = fn(*args, **kwargs)\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:478: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/youtube/y2_subtitle_handler.py:38: in download_srt\n    transcripts = YouTubeTranscriptApi.list_transcripts(self._video_id)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/youtube_transcript_api/_api.py:71: in list_transcripts\n    return TranscriptListFetcher(http_client).fetch(video_id)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/youtube_transcript_api/_transcripts.py:48: in fetch\n    self._extract_captions_json(self._fetch_video_html(video_id), video_id),\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <youtube_transcript_api._transcripts.TranscriptListFetcher object at 0x7fce49f2df10>\nhtml = '<!DOCTYPE html><html style=\"font-size: 10px;font-family: Roboto, Arial, sans-serif;\" lang=\"en\" darker-dark-theme dark...once=\"EjgJf9q9S-7Ki_HsAR-n3A\">if (window.ytcsi) {ytcsi.infoGel({serverTimeMs:  468.0 }, \\'\\');}</script></body></html>'\nvideo_id = 'fVcKBox97P0'\n\n    def _extract_captions_json(self, html, video_id):\n        splitted_html = html.split('\"captions\":')\n    \n        if len(splitted_html) <= 1:\n            if video_id.startswith('http://') or video_id.startswith('https://'):\n                raise InvalidVideoId(video_id)\n            if 'class=\"g-recaptcha\"' in html:\n                raise TooManyRequests(video_id)\n            if '\"playabilityStatus\":' not in html:\n                raise VideoUnavailable(video_id)\n    \n>           raise TranscriptsDisabled(video_id)\nE           youtube_transcript_api._errors.TranscriptsDisabled: \nE           Could not retrieve a transcript for the video https://www.youtube.com/watch?v=fVcKBox97P0! This is most likely caused by:\nE           \nE           Subtitles are disabled for this video\nE           \nE           If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/youtube_transcript_api/_transcripts.py:62: TranscriptsDisabled\n\nThe above exception was the direct cause of the following exception:\n\ntest_output_dir = '/home/runner/work/github-runner/github-runner/mypy/tests/lib/youtube/_out/test_y2_subtitle_handler'\n\n    def test_y2_srt_handler(test_output_dir):\n        \"\"\"\n        测试下载youtu字幕\n        \"\"\"\n        video_id = 'fVcKBox97P0'\n        en_srt_filepath = os.path.join(\n            test_output_dir, video_id + '_en.srt')\n    \n        zh_srt_filepath = os.path.join(\n            test_output_dir, video_id + '_zh.srt')\n    \n        api = Y2SubtitleHandler(video_id, en_srt_filepath, zh_srt_filepath)\n>       api.download_srt()\n\nmypy/tests/lib/youtube/test_y2_subtitle_handler.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:336: in wrapped_f\n    return copy(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:475: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:376: in iter\n    result = action(retry_state)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nrs = <RetryCallState 140523980643152: attempt #5; slept for 0.0; last result: failed (TranscriptsDisabled \nCould not retrie...tion needed to replicate the error. Also make sure that there are no open issues which already describe your problem!)>\n\n    def exc_check(rs: \"RetryCallState\") -> None:\n        fut = t.cast(Future, rs.outcome)\n        retry_exc = self.retry_error_cls(fut)\n        if self.reraise:\n            raise retry_exc.reraise()\n>       raise retry_exc from fut.exception()\nE       tenacity.RetryError: RetryError[<Future at 0x7fce5d746490 state=finished raised TranscriptsDisabled>]\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:419: RetryError","steps":[],"attachments":[{"uid":"11a745ca012a2f43","name":"log","source":"11a745ca012a2f43.txt","type":"text/plain","size":681}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"test_output_dir::0","time":{"start":1726243856160,"stop":1726243856160,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"copy_config_to_dir::finish_callback","time":{"start":1726243856161,"stop":1726243856162,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"youtube"},{"name":"parentSuite","value":"lib.youtube"},{"name":"suite","value":"test_y2_subtitle_handler"},{"name":"host","value":"fv-az702-656"},{"name":"thread","value":"9827-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"lib.youtube.test_y2_subtitle_handler"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["youtube"]},"source":"cffc23da9debf0ae.json","parameterValues":[]}